# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2a5fb640095fef42ec6a3a21a7d07d915a89be81128f3fa56364e286d221a96c22add86e7a6791da7912044ff185df742990e39c03a93ee9ce8e161f8e058d28

test:
  secret_key_base: adf3b2a189088bbee95b02ebad5eb2e6f0924801dea04c588380e43736b33c1d39fbcc56dfbb394ec3a4ae3c50f605a53912097becad4e2109bdaef0123a3868

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
